# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='menu_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
