# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromio', '0002_productprice_tax_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='configurations',
            field=models.TextField(blank=True, verbose_name='configurations'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.CharField(choices=[(b'EUR', b'EUR')], max_length=3, verbose_name='currency'),
        ),
    ]
