# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromio', '0003_auto_20160905_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='material',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='size',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
