# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160905_0910'),
        ('cromio', '0006_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWithData',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Order')),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.order',),
        ),
    ]
